/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'liangyt' at '16-1-6 下午4:59' with Gradle 2.6
 *
 * @author liangyt, @date 16-1-6 下午4:59
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
